[project]
name = "bmate-test-coding"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4>=4.13.5",
    "geopy>=2.4.1",
    "googletrans==4.0.0rc1",
    "requests>=2.32.5",
    "selenium>=4.35.0",
]
